module memsys_tb_top import o3_types_pkg::*; #(
    parameter int SETS=64,WAYS=8,MSHRS=4,WBS=2,
    parameter bit RFO=1,
    parameter int L2_SETS=2,L2_WAYS=2,SLOTS=2,
    localparam int ID_W=o3_cfg_pkg::O3_CFG.be.l2.axi_id_bits,DATA_W=o3_cfg_pkg::O3_CFG.be.l2.axi_data_bits
)(input logic clk,rst,
    input logic [1:0] cpu_valid, output logic [1:0] cpu_ready,
    input dcache_req_t cpu0,cpu1,s1_cpu0,s1_cpu1,
    output dcache_resp_t resp0,resp1,
    input rob_idx_t rob_head_i,
    input logic flush_i,resolution_valid_i,resolution_mispredict_i,input br_tag_t resolution_tag_i,
    // Reservations for LSU's IS stage; the CPU S0 request arrives two cycles later.
    output logic full_line_busy_o,output logic internal_busy_o,
    input logic st_req_valid_i,output logic st_req_ready_o,input dcache_req_t st_req_i,output dcache_resp_t st_resp_o,
    input logic ptw_req_valid_i,output logic ptw_req_ready_o,input dcache_req_t ptw_req_i,output dcache_resp_t ptw_resp_o,
    input logic pte_ad_req_valid_i,output logic pte_ad_req_ready_o,input pte_ad_req_t pte_ad_req_i,
    output pte_ad_resp_t pte_ad_resp_o,input xlate_epoch_t cur_epoch_i,input pmp_state_t pmp_i,
    output dc_wake_t wake_o,
    output logic l2_req_valid_o,output logic l2_req_ready_i,output coh_req_t l2_req_o,
    output logic l2_resp_valid_i,output coh_rsp_down_t l2_resp_i,output logic l2_resp_ready_o,
    output logic rsp_up_valid_o,output logic rsp_up_ready_i,output coh_rsp_up_t rsp_up_o,
    output logic snp_valid_i,output logic snp_ready_o,output coh_snp_t snp_i,
    output logic idle_o,output fatal_evt_t fatal_o,output be_perf_t perf_o,
    output logic init_done,
    output logic mon_ps_valid,mon_ps_write,mon_probe_hold,mon_probe_read,mon_ps_alloc,
    output logic [MSHRS-1:0] mon_ms_valid,
    output logic [WBS-1:0] mon_wb_valid,
    output logic [SETS*WAYS*2-1:0] mon_state,
    output logic [SETS*WAYS*26-1:0] mon_addr,
    output logic [SETS*(WAYS-1)-1:0] mon_plru,
    output logic [31:0] widths,
    output logic                  m_axi_awvalid,
    input  logic                  m_axi_awready,
    output logic [ID_W-1:0]   m_axi_awid,
    output logic [PADDR_W-1:0]    m_axi_awaddr,
    output logic [7:0]            m_axi_awlen,
    output logic [2:0]            m_axi_awsize,
    output logic [1:0]            m_axi_awburst,
    output logic                  m_axi_wvalid,
    input  logic                  m_axi_wready,
    output logic [DATA_W-1:0] m_axi_wdata,
    output logic [DATA_W/8-1:0] m_axi_wstrb,
    output logic                  m_axi_wlast,
    input  logic                  m_axi_bvalid,
    output logic                  m_axi_bready,
    input  logic [ID_W-1:0]   m_axi_bid,
    input  logic [1:0]            m_axi_bresp,
    output logic                  m_axi_arvalid,
    input  logic                  m_axi_arready,
    output logic [ID_W-1:0]   m_axi_arid,
    output logic [PADDR_W-1:0]    m_axi_araddr,
    output logic [7:0]            m_axi_arlen,
    output logic [2:0]            m_axi_arsize,
    output logic [1:0]            m_axi_arburst,
    input  logic                  m_axi_rvalid,
    output logic                  m_axi_rready,
    input  logic [ID_W-1:0]   m_axi_rid,
    input  logic [DATA_W-1:0] m_axi_rdata,
    input  logic [1:0]            m_axi_rresp,
    input  logic                  m_axi_rlast,
    output logic l2_init_done,
    output fatal_evt_t l2_fatal_o,
    output logic [L2_SETS*L2_WAYS-1:0] l2_mon_valid,l2_mon_sharer,
    output logic [L2_SETS*L2_WAYS*2-1:0] l2_mon_state,
    output logic [L2_SETS*L2_WAYS*26-1:0] l2_mon_addr,
    output logic [SLOTS-1:0] l2_mon_slot_busy,
    input logic l1i_req_valid_i,output logic l1i_req_ready_o,input coh_req_t l1i_req_i,
    output logic l1i_resp_valid_o,input logic l1i_resp_ready_i,output coh_rsp_down_t l1i_resp_o
);
    dcache_tb_top #(.SETS(SETS),.WAYS(WAYS),.MSHRS(MSHRS),.WBS(WBS),.RFO(RFO)) cache(
        .context_valid_i(1'b0),.test_priv_i(2'd3),.rsv_clear_i(1'b0),
        .mon_rsv_valid(),.mon_rsv_window(),.mon_atomic_hold(),
        .dma_invalidate_o(),.dma_line_o(),.irreversible_o(),.*);
    l2_home_tb_top #(.SETS(L2_SETS),.WAYS(L2_WAYS),.SLOTS(SLOTS)) home(
        .l1d_req_valid_i(l2_req_valid_o),.l1d_req_ready_o(l2_req_ready_i),.l1d_req_i(l2_req_o),
        .l1d_resp_valid_o(l2_resp_valid_i),.l1d_resp_ready_i(l2_resp_ready_o),.l1d_resp_o(l2_resp_i),
        .dma_req_valid_i(1'b0),.dma_req_i('0),.dma_resp_ready_i(1'b1),
        .dma_req_ready_o(),.dma_resp_valid_o(),.dma_resp_o(),
        .rsp_up_valid_i(rsp_up_valid_o),.rsp_up_ready_o(rsp_up_ready_i),.rsp_up_i(rsp_up_o),
        .snp_valid_o(snp_valid_i),.snp_ready_i(snp_ready_o),.snp_o(snp_i),
        .fatal_o(l2_fatal_o),.perf_o(),.init_done(l2_init_done),
        .mon_valid(l2_mon_valid),.mon_sharer(l2_mon_sharer),.mon_state(l2_mon_state),
        .mon_addr(l2_mon_addr),.mon_slot_busy(l2_mon_slot_busy),.mon_slot_full(),.*);
endmodule
