// Generated by scripts/gen_platform_pkg.py; do not edit.
// Platform SHA256: b82edabbaf28fd545680030801e1fd5f1ab163ae72c0ad5d93a36173c4be6e30
package o3_platform_pkg;
    typedef struct packed {
        logic exists, readable, writable, executable, cacheable, device, amo, rsrv;
    } pma_attr_t;
    localparam logic [63:0] MACHINE_TIMER_BASE = 64'h0000000002000000;
    localparam logic [64:0] MACHINE_TIMER_END = 65'h00000000002010000;
    localparam logic [63:0] PLIC_BASE = 64'h000000000c000000;
    localparam logic [64:0] PLIC_END = 65'h00000000010000000;
    localparam logic [63:0] BOOT_ROM_BASE = 64'h0000000010000000;
    localparam logic [64:0] BOOT_ROM_END = 65'h00000000010010000;
    localparam logic [63:0] LINUX_BOOT_ROM_BASE = 64'h0000000010010000;
    localparam logic [64:0] LINUX_BOOT_ROM_END = 65'h00000000010020000;
    localparam logic [63:0] SRAM_BASE = 64'h0000000011000000;
    localparam logic [64:0] SRAM_END = 65'h00000000011010000;
    localparam logic [63:0] LITEX_MMIO_BASE = 64'h0000000012000000;
    localparam logic [64:0] LITEX_MMIO_END = 65'h00000000012100000;
    localparam logic [63:0] MAIN_RAM_BASE = 64'h0000000080000000;
    localparam logic [64:0] MAIN_RAM_END = 65'h00000000100000000;
    function automatic pma_attr_t lookup(input logic [63:0] addr, input int unsigned bytes);
        pma_attr_t attr; logic [64:0] finish;
        attr='0; finish={1'b0,addr}+65'(bytes);
        if(bytes>0 && addr>=MACHINE_TIMER_BASE && finish<=MACHINE_TIMER_END)
            attr=8'b11100100;
        if(bytes>0 && addr>=PLIC_BASE && finish<=PLIC_END)
            attr=8'b11100100;
        if(bytes>0 && addr>=BOOT_ROM_BASE && finish<=BOOT_ROM_END)
            attr=8'b11011000;
        if(bytes>0 && addr>=LINUX_BOOT_ROM_BASE && finish<=LINUX_BOOT_ROM_END)
            attr=8'b11011000;
        if(bytes>0 && addr>=SRAM_BASE && finish<=SRAM_END)
            attr=8'b11111011;
        if(bytes>0 && addr>=LITEX_MMIO_BASE && finish<=LITEX_MMIO_END)
            attr=8'b11100100;
        if(bytes>0 && addr>=MAIN_RAM_BASE && finish<=MAIN_RAM_END)
            attr=8'b11111011;
        return attr;
    endfunction
endpackage
