#!/usr/bin/env python3
"""Generate the O3 PMA package from its sole platform JSON authority."""
import argparse
import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "litex_wrapper"))
from o3.platform import load_platform


def render(path):
    cfg = load_platform(path)
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    lines = ["// Generated by scripts/gen_platform_pkg.py; do not edit.",
             f"// Platform SHA256: {digest}", "package o3_platform_pkg;",
             "    typedef struct packed {",
             "        logic exists, readable, writable, executable, cacheable, device, amo, rsrv;",
             "    } pma_attr_t;"]
    for r in cfg["regions"]:
        name, base, end = r["name"].upper(), int(r["origin"], 0), int(r["origin"], 0) + int(r["size"], 0)
        lines += [f"    localparam logic [63:0] {name}_BASE = 64'h{base:016x};",
                  f"    localparam logic [64:0] {name}_END = 65'h{end:017x};"]
    lines += ["    function automatic pma_attr_t lookup(input logic [63:0] addr, input int unsigned bytes);",
              "        pma_attr_t attr; logic [64:0] finish;",
              "        attr='0; finish={1'b0,addr}+65'(bytes);"]
    for r in cfg["regions"]:
        n = r["name"].upper()
        bits = [True] + [r[k] for k in ("readable", "writable", "executable", "cacheable", "device")] + [r["amo"] == "arithmetic", r["reservability"] == "eventual"]
        value = "".join(str(int(b)) for b in bits)
        lines += [f"        if(bytes>0 && addr>={n}_BASE && finish<={n}_END)",
                  f"            attr=8'b{value};"]
    lines += ["        return attr;", "    endfunction", "endpackage", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--platform", type=Path, default=ROOT / "config/o3_platform.json")
    parser.add_argument("--output", type=Path, default=ROOT / "rtl/common/o3_platform_pkg.sv")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render(args.platform)
    if args.check:
        if not args.output.exists() or args.output.read_text() != expected:
            raise SystemExit("generated platform package is stale")
    else:
        args.output.write_text(expected)


if __name__ == "__main__":
    main()
